[package]
name = "sim_cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
grav_core = { path = "../grav_core"}
anyhow.workspace = true
clap = { version = "4", features = ["derive"] }
