[workspace]
members = ["grav_core", "sim_cli"]
resolver = "2"

[workspace.package]
edition = "2024"
version = "0.1.0"
license = "MIT-0"
repository = "https://github.com/mmkzer0/bh-sim"

[workspace.dependencies]
anyhow = "1"
thiserror = "1"
serde = { version = "1", features = ["derive"] }
